all: isFuntionOrOpenParentesis isDigit isArgumentSeparator isOperator
isFuntionOrOpenParentesis:
	pic src/isFuntionOrOpenParentesis.tr | groff > isFuntionOrOpenParentesis.ps
	rm eps/isFuntionOrOpenParentesis.eps -f
	ps2eps isFuntionOrOpenParentesis.ps
	rm isFuntionOrOpenParentesis.ps
	mv isFuntionOrOpenParentesis.eps eps/SYA
isDigit:
	pic src/isDigit.tr | groff > isDigit.ps
	rm eps/isDigit.eps -f
	ps2eps isDigit.ps
	rm isDigit.ps
	mv isDigit.eps eps/SYA
isArgumentSeparator:
	pic src/isArgumentSeparator.tr | groff > isArgumentSeparator.ps
	rm eps/isArgumentSeparator.eps -f
	ps2eps isArgumentSeparator.ps
	rm isArgumentSeparator.ps
	mv isArgumentSeparator.eps eps/SYA
isOperator:
	pic src/isOperator.tr | groff > isOperator.ps
	rm eps/isOperator.eps -f
	ps2eps isOperator.ps
	rm isOperator.ps
	mv isOperator.eps eps/SYA
isCloseParentesis:
	pic src/isCloseParentesis.tr | groff > isCloseParentesis.ps
	rm eps/isCloseParentesis.eps -f
	ps2eps isCloseParentesis.ps
	rm isCloseParentesis.ps
	mv isCloseParentesis.eps eps/SYA
token:
	pic src/token.tr | groff > token.ps
	rm eps/token.eps -f
	ps2eps token.ps
	rm token.ps
	mv token.eps eps/SYA
